name: fairfluids
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  # Core dependencies
  - pydantic>=2.0.0
  - pydantic-xml>=2.0.0
  - lxml>=4.6.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  # Jupyter environment
  - jupyter
  - ipykernel
  # Development dependencies
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - isort>=5.0.0
  - flake8>=5.0.0
  - mypy>=1.0.0
  # Documentation
  - sphinx>=5.0.0
  - sphinx-rtd-theme>=1.0.0
  - myst-parser>=0.18.0
  # Scientific computing
  - matplotlib
  - seaborn
  - scipy
  - rdkit
  # Install the package in development mode
  - pip:
      - -e .
