# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (13)
# #########################################################################

class Author(BaseModel):
    given_name: typing.Optional[str] = None
    family_name: typing.Optional[str] = None
    email: typing.Optional[str] = None
    orcid: typing.Optional[str] = None
    affiliation: typing.Optional[str] = None

class BaseUnit(BaseModel):
    kind: typing.Optional[types.UnitType] = None
    exponent: typing.Optional[int] = None
    multiplier: typing.Optional[float] = None
    scale: typing.Optional[float] = None

class Citation(BaseModel):
    litType: typing.Optional[types.LitType] = None
    author: typing.List["Author"]
    doi: typing.Optional[str] = None
    page: typing.Optional[str] = None
    pub_name: typing.Optional[str] = None
    title: typing.Optional[str] = None
    lit_volume_num: typing.Optional[str] = None
    url_citation: typing.Optional[str] = None
    publication_year: typing.Optional[str] = None

class Compound(BaseModel):
    pubChemID: typing.Optional[int] = None
    compound_identifier: typing.Optional[int] = None
    commonName: typing.Optional[str] = None
    SELFIE: typing.Optional[str] = None
    name_IUPAC: typing.Optional[str] = None
    standard_InChI: typing.Optional[str] = None
    standard_InChI_key: typing.Optional[str] = None

class FAIRFluidsDocument(BaseModel):
    version: typing.Optional["Version"] = None
    citation: typing.Optional["Citation"] = None
    compound: typing.List["Compound"]
    fluid: typing.List["Fluid"]

class Fluid(BaseModel):
    compounds: typing.List[int]
    property: typing.List["Property"]
    parameter: typing.List["Parameter"]
    measurement: typing.List["Measurement"]

class Measurement(BaseModel):
    measurement_id: typing.Optional[int] = None
    source_doi: typing.Optional[str] = None
    propertyValue: typing.List["PropertyValue"]
    parameterValue: typing.List["ParameterValue"]
    method: typing.Optional[types.Method] = None
    method_description: typing.Optional[str] = None

class Parameter(BaseModel):
    parameterID: typing.Optional[int] = None
    parameter: typing.Optional[types.Parameters] = None
    unit: typing.Optional["UnitDefinition"] = None
    associated_compound: typing.Optional[int] = None

class ParameterValue(BaseModel):
    param_id: typing.Optional[int] = None
    paramDigits: typing.Optional[int] = None
    paramValue: typing.Optional[float] = None
    uncertainty: typing.Optional[float] = None

class Property(BaseModel):
    propertyID: typing.Optional[int] = None
    properties: typing.Optional[types.Properties] = None
    unit: typing.Optional["UnitDefinition"] = None

class PropertyValue(BaseModel):
    prop_id: typing.Optional[int] = None
    propDigits: typing.Optional[int] = None
    propValue: typing.Optional[float] = None
    uncertainty: typing.Optional[float] = None

class UnitDefinition(BaseModel):
    id: typing.Optional[str] = None
    name: typing.Optional[str] = None
    base_units: typing.List["BaseUnit"]

class Version(BaseModel):
    versionMajor: typing.Optional[int] = None
    versionMinor: typing.Optional[int] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
