# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Author": types.Author,
    "stream_types.Author": stream_types.Author,

    "types.C_id": types.C_id,
    "stream_types.C_id": stream_types.C_id,

    "types.Citation": types.Citation,
    "stream_types.Citation": stream_types.Citation,

    "types.Compound": types.Compound,
    "stream_types.Compound": stream_types.Compound,

    "types.FAIRFluidsDocument": types.FAIRFluidsDocument,
    "stream_types.FAIRFluidsDocument": stream_types.FAIRFluidsDocument,

    "types.Fluid": types.Fluid,
    "stream_types.Fluid": stream_types.Fluid,

    "types.NumValue": types.NumValue,
    "stream_types.NumValue": stream_types.NumValue,

    "types.Parameter": types.Parameter,
    "stream_types.Parameter": stream_types.Parameter,

    "types.ParameterType": types.ParameterType,
    "stream_types.ParameterType": stream_types.ParameterType,

    "types.ParameterValue": types.ParameterValue,
    "stream_types.ParameterValue": stream_types.ParameterValue,

    "types.Property": types.Property,
    "stream_types.Property": stream_types.Property,

    "types.PropertyValue": types.PropertyValue,
    "stream_types.PropertyValue": stream_types.PropertyValue,

    "types.Property_Information": types.Property_Information,
    "stream_types.Property_Information": stream_types.Property_Information,

    "types.Version": types.Version,
    "stream_types.Version": stream_types.Version,


    "types.BioVariables": types.BioVariables,

    "types.ComponentComposition": types.ComponentComposition,

    "types.LitType": types.LitType,

    "types.Miscellaneous": types.Miscellaneous,

    "types.ParticipantAmount": types.ParticipantAmount,

    "types.Pressure": types.Pressure,

    "types.SolventComposition": types.SolventComposition,

    "types.Temperature": types.Temperature,

}