# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
from baml_py import type_builder
from baml_py import baml_py
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME

class TypeBuilder(type_builder.TypeBuilder):
    def __init__(self):
        super().__init__(classes=set(
          ["Author","C_id","Citation","Compound","FAIRFluidsDocument","Fluid","NumValue","Parameter","ParameterType","ParameterValue","Property","PropertyValue","Property_Information","Version",]
        ), enums=set(
          ["BioVariables","ComponentComposition","LitType","Miscellaneous","ParticipantAmount","Pressure","SolventComposition","Temperature",]
        ), runtime=DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME)

    # #########################################################################
    # Generated enums 8
    # #########################################################################

    @property
    def BioVariables(self) -> "BioVariablesViewer":
        return BioVariablesViewer(self)

    @property
    def ComponentComposition(self) -> "ComponentCompositionViewer":
        return ComponentCompositionViewer(self)

    @property
    def LitType(self) -> "LitTypeViewer":
        return LitTypeViewer(self)

    @property
    def Miscellaneous(self) -> "MiscellaneousViewer":
        return MiscellaneousViewer(self)

    @property
    def ParticipantAmount(self) -> "ParticipantAmountViewer":
        return ParticipantAmountViewer(self)

    @property
    def Pressure(self) -> "PressureViewer":
        return PressureViewer(self)

    @property
    def SolventComposition(self) -> "SolventCompositionViewer":
        return SolventCompositionViewer(self)

    @property
    def Temperature(self) -> "TemperatureViewer":
        return TemperatureViewer(self)


    # #########################################################################
    # Generated classes 14
    # #########################################################################

    @property
    def Author(self) -> "AuthorViewer":
        return AuthorViewer(self)

    @property
    def C_id(self) -> "C_idViewer":
        return C_idViewer(self)

    @property
    def Citation(self) -> "CitationViewer":
        return CitationViewer(self)

    @property
    def Compound(self) -> "CompoundViewer":
        return CompoundViewer(self)

    @property
    def FAIRFluidsDocument(self) -> "FAIRFluidsDocumentViewer":
        return FAIRFluidsDocumentViewer(self)

    @property
    def Fluid(self) -> "FluidViewer":
        return FluidViewer(self)

    @property
    def NumValue(self) -> "NumValueViewer":
        return NumValueViewer(self)

    @property
    def Parameter(self) -> "ParameterViewer":
        return ParameterViewer(self)

    @property
    def ParameterType(self) -> "ParameterTypeViewer":
        return ParameterTypeViewer(self)

    @property
    def ParameterValue(self) -> "ParameterValueViewer":
        return ParameterValueViewer(self)

    @property
    def Property(self) -> "PropertyViewer":
        return PropertyViewer(self)

    @property
    def PropertyValue(self) -> "PropertyValueViewer":
        return PropertyValueViewer(self)

    @property
    def Property_Information(self) -> "Property_InformationViewer":
        return Property_InformationViewer(self)

    @property
    def Version(self) -> "VersionViewer":
        return VersionViewer(self)



# #########################################################################
# Generated enums 8
# #########################################################################

class BioVariablesAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("BioVariables")
        self._values: typing.Set[str] = set([  "PH",  "IONIC_STRENGTH_MOLALITY_BASIS_MOLKG",  "IONIC_STRENGTH_AMOUNT_CONCENTRATION_BASIS_MOLDM3",  "PC_AMOUNT_CONCENTRATION_BASIS",  "SOLVENT_PC_AMOUNT_CONCENTRATION_BASIS",  ])
        self._vals = BioVariablesValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "BioVariablesValues":
        return self._vals


class BioVariablesViewer(BioVariablesAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class BioVariablesValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def PH(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PH"))
    
    @property
    def IONIC_STRENGTH_MOLALITY_BASIS_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IONIC_STRENGTH_MOLALITY_BASIS_MOLKG"))
    
    @property
    def IONIC_STRENGTH_AMOUNT_CONCENTRATION_BASIS_MOLDM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("IONIC_STRENGTH_AMOUNT_CONCENTRATION_BASIS_MOLDM3"))
    
    @property
    def PC_AMOUNT_CONCENTRATION_BASIS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PC_AMOUNT_CONCENTRATION_BASIS"))
    
    @property
    def SOLVENT_PC_AMOUNT_CONCENTRATION_BASIS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_PC_AMOUNT_CONCENTRATION_BASIS"))
    
    


class ComponentCompositionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ComponentComposition")
        self._values: typing.Set[str] = set([  "MOLE_FRACTION",  "MASS_FRACTION",  "MOLALITY_MOLKG",  "AMOUNT_CONCENTRATION_MOLARITY_MOLDM3",  "VOLUME_FRACTION",  "RATIO_OF_AMOUNT_OF_SOLUTE_TO_MASS_OF_SOLUTION_MOLKG",  "RATIO_OF_MASS_OF_SOLUTE_TO_VOLUME_OF_SOLUTION_KGM3",  "AMOUNT_RATIO_OF_SOLUTE_TO_SOLVENT",  "MASS_RATIO_OF_SOLUTE_TO_SOLVENT",  "VOLUME_RATIO_OF_SOLUTE_TO_SOLVENT",  "INITIAL_MOLE_FRACTION_OF_SOLUTE",  "FINAL_MOLE_FRACTION_OF_SOLUTE",  "INITIAL_MASS_FRACTION_OF_SOLUTE",  "FINAL_MASS_FRACTION_OF_SOLUTE",  "INITIAL_MOLALITY_OF_SOLUTE_MOLKG",  "FINAL_MOLALITY_OF_SOLUTE_MOLKG",  ])
        self._vals = ComponentCompositionValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ComponentCompositionValues":
        return self._vals


class ComponentCompositionViewer(ComponentCompositionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ComponentCompositionValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def MOLE_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MOLE_FRACTION"))
    
    @property
    def MASS_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MASS_FRACTION"))
    
    @property
    def MOLALITY_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MOLALITY_MOLKG"))
    
    @property
    def AMOUNT_CONCENTRATION_MOLARITY_MOLDM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AMOUNT_CONCENTRATION_MOLARITY_MOLDM3"))
    
    @property
    def VOLUME_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("VOLUME_FRACTION"))
    
    @property
    def RATIO_OF_AMOUNT_OF_SOLUTE_TO_MASS_OF_SOLUTION_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RATIO_OF_AMOUNT_OF_SOLUTE_TO_MASS_OF_SOLUTION_MOLKG"))
    
    @property
    def RATIO_OF_MASS_OF_SOLUTE_TO_VOLUME_OF_SOLUTION_KGM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RATIO_OF_MASS_OF_SOLUTE_TO_VOLUME_OF_SOLUTION_KGM3"))
    
    @property
    def AMOUNT_RATIO_OF_SOLUTE_TO_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AMOUNT_RATIO_OF_SOLUTE_TO_SOLVENT"))
    
    @property
    def MASS_RATIO_OF_SOLUTE_TO_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MASS_RATIO_OF_SOLUTE_TO_SOLVENT"))
    
    @property
    def VOLUME_RATIO_OF_SOLUTE_TO_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("VOLUME_RATIO_OF_SOLUTE_TO_SOLVENT"))
    
    @property
    def INITIAL_MOLE_FRACTION_OF_SOLUTE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INITIAL_MOLE_FRACTION_OF_SOLUTE"))
    
    @property
    def FINAL_MOLE_FRACTION_OF_SOLUTE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FINAL_MOLE_FRACTION_OF_SOLUTE"))
    
    @property
    def INITIAL_MASS_FRACTION_OF_SOLUTE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INITIAL_MASS_FRACTION_OF_SOLUTE"))
    
    @property
    def FINAL_MASS_FRACTION_OF_SOLUTE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FINAL_MASS_FRACTION_OF_SOLUTE"))
    
    @property
    def INITIAL_MOLALITY_OF_SOLUTE_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("INITIAL_MOLALITY_OF_SOLUTE_MOLKG"))
    
    @property
    def FINAL_MOLALITY_OF_SOLUTE_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FINAL_MOLALITY_OF_SOLUTE_MOLKG"))
    
    


class LitTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("LitType")
        self._values: typing.Set[str] = set([  "BOOK",  "JOURNAL",  "REPORT",  "PATENT",  "THESIS",  "CONFERENCEPROCEEDINGS",  "ARCHIVEDDOCUMENT",  "PERSONALCORRESPONDENCE",  "PUBLISHEDTRANSLATION",  "UNSPECIFIED",  ])
        self._vals = LitTypeValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "LitTypeValues":
        return self._vals


class LitTypeViewer(LitTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class LitTypeValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def BOOK(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("BOOK"))
    
    @property
    def JOURNAL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("JOURNAL"))
    
    @property
    def REPORT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("REPORT"))
    
    @property
    def PATENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PATENT"))
    
    @property
    def THESIS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("THESIS"))
    
    @property
    def CONFERENCEPROCEEDINGS(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("CONFERENCEPROCEEDINGS"))
    
    @property
    def ARCHIVEDDOCUMENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ARCHIVEDDOCUMENT"))
    
    @property
    def PERSONALCORRESPONDENCE(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PERSONALCORRESPONDENCE"))
    
    @property
    def PUBLISHEDTRANSLATION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PUBLISHEDTRANSLATION"))
    
    @property
    def UNSPECIFIED(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UNSPECIFIED"))
    
    


class MiscellaneousAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Miscellaneous")
        self._values: typing.Set[str] = set([  "WAVELENGTH_NM",  "FREQUENCY_MHZ",  "MOLAR_VOLUME_M3MOL",  "SPECIFIC_VOLUME_M3KG",  "MASS_DENSITY_KGM3",  "AMOUNT_DENSITY_MOLM3",  "MOLAR_ENTROPY_JKMOL",  "RELATIVE_ACTIVITY",  "ACTIVITY_COEFFICIENT",  ])
        self._vals = MiscellaneousValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "MiscellaneousValues":
        return self._vals


class MiscellaneousViewer(MiscellaneousAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class MiscellaneousValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def WAVELENGTH_NM(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("WAVELENGTH_NM"))
    
    @property
    def FREQUENCY_MHZ(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("FREQUENCY_MHZ"))
    
    @property
    def MOLAR_VOLUME_M3MOL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MOLAR_VOLUME_M3MOL"))
    
    @property
    def SPECIFIC_VOLUME_M3KG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SPECIFIC_VOLUME_M3KG"))
    
    @property
    def MASS_DENSITY_KGM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MASS_DENSITY_KGM3"))
    
    @property
    def AMOUNT_DENSITY_MOLM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AMOUNT_DENSITY_MOLM3"))
    
    @property
    def MOLAR_ENTROPY_JKMOL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MOLAR_ENTROPY_JKMOL"))
    
    @property
    def RELATIVE_ACTIVITY(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("RELATIVE_ACTIVITY"))
    
    @property
    def ACTIVITY_COEFFICIENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("ACTIVITY_COEFFICIENT"))
    
    


class ParticipantAmountAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("ParticipantAmount")
        self._values: typing.Set[str] = set([  "AMOUNT_MOL",  "MASS_KG",  ])
        self._vals = ParticipantAmountValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "ParticipantAmountValues":
        return self._vals


class ParticipantAmountViewer(ParticipantAmountAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class ParticipantAmountValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def AMOUNT_MOL(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("AMOUNT_MOL"))
    
    @property
    def MASS_KG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("MASS_KG"))
    
    


class PressureAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Pressure")
        self._values: typing.Set[str] = set([  "PRESSURE_KPA",  "PARTIAL_PRESSURE_KPA",  "UPPER_PRESSURE_KPA",  "LOWER_PRESSURE_KPA",  ])
        self._vals = PressureValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "PressureValues":
        return self._vals


class PressureViewer(PressureAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class PressureValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def PRESSURE_KPA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PRESSURE_KPA"))
    
    @property
    def PARTIAL_PRESSURE_KPA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("PARTIAL_PRESSURE_KPA"))
    
    @property
    def UPPER_PRESSURE_KPA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UPPER_PRESSURE_KPA"))
    
    @property
    def LOWER_PRESSURE_KPA(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOWER_PRESSURE_KPA"))
    
    


class SolventCompositionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("SolventComposition")
        self._values: typing.Set[str] = set([  "SOLVENT_MOLE_FRACTION",  "SOLVENT_MASS_FRACTION",  "SOLVENT_VOLUME_FRACTION",  "SOLVENT_MOLALITY_MOLKG",  "SOLVENT_AMOUNT_CONCENTRATION_MOLARITY_MOLDM3",  "SOLVENT_AMOUNT_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT",  "SOLVENT_MASS_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT",  "SOLVENT_VOLUME_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT",  "SOLVENT_RATIO_OF_AMOUNT_OF_COMPONENT_TO_MASS_OF_SOLVENT_MOLKG",  "SOLVENT_RATIO_OF_COMPONENT_MASS_TO_VOLUME_OF_SOLVENT_KGM3",  ])
        self._vals = SolventCompositionValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "SolventCompositionValues":
        return self._vals


class SolventCompositionViewer(SolventCompositionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class SolventCompositionValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def SOLVENT_MOLE_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_MOLE_FRACTION"))
    
    @property
    def SOLVENT_MASS_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_MASS_FRACTION"))
    
    @property
    def SOLVENT_VOLUME_FRACTION(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_VOLUME_FRACTION"))
    
    @property
    def SOLVENT_MOLALITY_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_MOLALITY_MOLKG"))
    
    @property
    def SOLVENT_AMOUNT_CONCENTRATION_MOLARITY_MOLDM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_AMOUNT_CONCENTRATION_MOLARITY_MOLDM3"))
    
    @property
    def SOLVENT_AMOUNT_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_AMOUNT_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT"))
    
    @property
    def SOLVENT_MASS_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_MASS_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT"))
    
    @property
    def SOLVENT_VOLUME_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_VOLUME_RATIO_OF_COMPONENT_TO_OTHER_COMPONENT_OF_BINARY_SOLVENT"))
    
    @property
    def SOLVENT_RATIO_OF_AMOUNT_OF_COMPONENT_TO_MASS_OF_SOLVENT_MOLKG(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_RATIO_OF_AMOUNT_OF_COMPONENT_TO_MASS_OF_SOLVENT_MOLKG"))
    
    @property
    def SOLVENT_RATIO_OF_COMPONENT_MASS_TO_VOLUME_OF_SOLVENT_KGM3(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("SOLVENT_RATIO_OF_COMPONENT_MASS_TO_VOLUME_OF_SOLVENT_KGM3"))
    
    


class TemperatureAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.enum("Temperature")
        self._values: typing.Set[str] = set([  "TEMPERATURE_K",  "UPPER_TEMPERATURE_K",  "LOWER_TEMPERATURE_K",  ])
        self._vals = TemperatureValues(self._bldr, self._values)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def values(self) -> "TemperatureValues":
        return self._vals


class TemperatureViewer(TemperatureAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_values(self) -> typing.List[typing.Tuple[str, type_builder.EnumValueViewer]]:
        return [(name, type_builder.EnumValueViewer(self._bldr.value(name))) for name in self._values]
    

class TemperatureValues:
    def __init__(self, enum_bldr: baml_py.EnumBuilder, values: typing.Set[str]):
        self.__bldr = enum_bldr
        self.__values = values # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def TEMPERATURE_K(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("TEMPERATURE_K"))
    
    @property
    def UPPER_TEMPERATURE_K(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("UPPER_TEMPERATURE_K"))
    
    @property
    def LOWER_TEMPERATURE_K(self) -> type_builder.EnumValueViewer:
        return type_builder.EnumValueViewer(self.__bldr.value("LOWER_TEMPERATURE_K"))
    
    



# #########################################################################
# Generated classes 14
# #########################################################################

class AuthorAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Author")
        self._properties: typing.Set[str] = set([  "given_name",  "family_name",  ])
        self._props = AuthorProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "AuthorProperties":
        return self._props


class AuthorViewer(AuthorAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class AuthorProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def given_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("given_name"))
    
    @property
    def family_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("family_name"))
    
    


class C_idAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("C_id")
        self._properties: typing.Set[str] = set([  "c_id",  ])
        self._props = C_idProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "C_idProperties":
        return self._props


class C_idViewer(C_idAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class C_idProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def c_id(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("c_id"))
    
    


class CitationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Citation")
        self._properties: typing.Set[str] = set([  "litType",  "author",  ])
        self._props = CitationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CitationProperties":
        return self._props


class CitationViewer(CitationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class CitationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def litType(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("litType"))
    
    @property
    def author(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("author"))
    
    


class CompoundAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Compound")
        self._properties: typing.Set[str] = set([  "pubChemID",  "compound_identifier",  "commonName",  "SELFIE",  "name_IUPAC",  "standard_InChI",  "standard_InChI_key",  ])
        self._props = CompoundProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "CompoundProperties":
        return self._props


class CompoundViewer(CompoundAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class CompoundProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def pubChemID(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pubChemID"))
    
    @property
    def compound_identifier(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("compound_identifier"))
    
    @property
    def commonName(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("commonName"))
    
    @property
    def SELFIE(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("SELFIE"))
    
    @property
    def name_IUPAC(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("name_IUPAC"))
    
    @property
    def standard_InChI(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("standard_InChI"))
    
    @property
    def standard_InChI_key(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("standard_InChI_key"))
    
    


class FAIRFluidsDocumentAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("FAIRFluidsDocument")
        self._properties: typing.Set[str] = set([  "version",  "citation",  "compound",  "fluid",  ])
        self._props = FAIRFluidsDocumentProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FAIRFluidsDocumentProperties":
        return self._props


class FAIRFluidsDocumentViewer(FAIRFluidsDocumentAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class FAIRFluidsDocumentProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def version(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("version"))
    
    @property
    def citation(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("citation"))
    
    @property
    def compound(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("compound"))
    
    @property
    def fluid(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("fluid"))
    
    


class FluidAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Fluid")
        self._properties: typing.Set[str] = set([  "components",  "source_doi",  "property",  "parameter",  "num_value",  ])
        self._props = FluidProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "FluidProperties":
        return self._props


class FluidViewer(FluidAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class FluidProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def components(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("components"))
    
    @property
    def source_doi(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("source_doi"))
    
    @property
    def property(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("property"))
    
    @property
    def parameter(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parameter"))
    
    @property
    def num_value(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("num_value"))
    
    


class NumValueAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("NumValue")
        self._properties: typing.Set[str] = set([  "propertyValue",  "parameterValue",  ])
        self._props = NumValueProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "NumValueProperties":
        return self._props


class NumValueViewer(NumValueAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class NumValueProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def propertyValue(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("propertyValue"))
    
    @property
    def parameterValue(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parameterValue"))
    
    


class ParameterAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Parameter")
        self._properties: typing.Set[str] = set([  "parameterID",  "parameterType",  "componentID",  ])
        self._props = ParameterProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ParameterProperties":
        return self._props


class ParameterViewer(ParameterAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ParameterProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def parameterID(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parameterID"))
    
    @property
    def parameterType(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("parameterType"))
    
    @property
    def componentID(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("componentID"))
    
    


class ParameterTypeAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ParameterType")
        self._properties: typing.Set[str] = set([  "bio_variables",  "component_composition",  "miscellaneous",  "participant_amount",  "pressure",  "solvent_composition",  "temperature",  ])
        self._props = ParameterTypeProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ParameterTypeProperties":
        return self._props


class ParameterTypeViewer(ParameterTypeAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ParameterTypeProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def bio_variables(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("bio_variables"))
    
    @property
    def component_composition(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("component_composition"))
    
    @property
    def miscellaneous(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("miscellaneous"))
    
    @property
    def participant_amount(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("participant_amount"))
    
    @property
    def pressure(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("pressure"))
    
    @property
    def solvent_composition(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("solvent_composition"))
    
    @property
    def temperature(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("temperature"))
    
    


class ParameterValueAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("ParameterValue")
        self._properties: typing.Set[str] = set([  "varDigits",  "varNumber",  "varValue",  ])
        self._props = ParameterValueProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "ParameterValueProperties":
        return self._props


class ParameterValueViewer(ParameterValueAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class ParameterValueProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def varDigits(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("varDigits"))
    
    @property
    def varNumber(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("varNumber"))
    
    @property
    def varValue(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("varValue"))
    
    


class PropertyAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Property")
        self._properties: typing.Set[str] = set([  "propertyID",  "property_information",  ])
        self._props = PropertyProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PropertyProperties":
        return self._props


class PropertyViewer(PropertyAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class PropertyProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def propertyID(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("propertyID"))
    
    @property
    def property_information(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("property_information"))
    
    


class PropertyValueAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("PropertyValue")
        self._properties: typing.Set[str] = set([  "propDigits",  "propNumber",  "propValue",  "uncertainty",  ])
        self._props = PropertyValueProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "PropertyValueProperties":
        return self._props


class PropertyValueViewer(PropertyValueAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class PropertyValueProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def propDigits(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("propDigits"))
    
    @property
    def propNumber(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("propNumber"))
    
    @property
    def propValue(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("propValue"))
    
    @property
    def uncertainty(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("uncertainty"))
    
    


class Property_InformationAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Property_Information")
        self._properties: typing.Set[str] = set([  "group",  "method",  "property_name",  ])
        self._props = Property_InformationProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "Property_InformationProperties":
        return self._props


class Property_InformationViewer(Property_InformationAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class Property_InformationProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def group(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("group"))
    
    @property
    def method(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("method"))
    
    @property
    def property_name(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("property_name"))
    
    


class VersionAst:
    def __init__(self, tb: type_builder.TypeBuilder):
        _tb = tb._tb # type: ignore (we know how to use this private attribute)
        self._bldr = _tb.class_("Version")
        self._properties: typing.Set[str] = set([  "versionMajor",  "versionMinor",  ])
        self._props = VersionProperties(self._bldr, self._properties)

    def type(self) -> baml_py.FieldType:
        return self._bldr.field()

    @property
    def props(self) -> "VersionProperties":
        return self._props


class VersionViewer(VersionAst):
    def __init__(self, tb: type_builder.TypeBuilder):
        super().__init__(tb)

    
    def list_properties(self) -> typing.List[typing.Tuple[str, type_builder.ClassPropertyViewer]]:
        return [(name, type_builder.ClassPropertyViewer(self._bldr.property(name))) for name in self._properties]
    


class VersionProperties:
    def __init__(self, bldr: baml_py.ClassBuilder, properties: typing.Set[str]):
        self.__bldr = bldr
        self.__properties = properties # type: ignore (we know how to use this private attribute) # noqa: F821

    
    
    @property
    def versionMajor(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("versionMajor"))
    
    @property
    def versionMinor(self) -> type_builder.ClassPropertyViewer:
        return type_builder.ClassPropertyViewer(self.__bldr.property("versionMinor"))
    
    

