# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Author": types.Author,
    "stream_types.Author": stream_types.Author,

    "types.BaseUnit": types.BaseUnit,
    "stream_types.BaseUnit": stream_types.BaseUnit,

    "types.Citation": types.Citation,
    "stream_types.Citation": stream_types.Citation,

    "types.Compound": types.Compound,
    "stream_types.Compound": stream_types.Compound,

    "types.FAIRFluidsDocument": types.FAIRFluidsDocument,
    "stream_types.FAIRFluidsDocument": stream_types.FAIRFluidsDocument,

    "types.Fluid": types.Fluid,
    "stream_types.Fluid": stream_types.Fluid,

    "types.Measurement": types.Measurement,
    "stream_types.Measurement": stream_types.Measurement,

    "types.Parameter": types.Parameter,
    "stream_types.Parameter": stream_types.Parameter,

    "types.ParameterValue": types.ParameterValue,
    "stream_types.ParameterValue": stream_types.ParameterValue,

    "types.Property": types.Property,
    "stream_types.Property": stream_types.Property,

    "types.PropertyValue": types.PropertyValue,
    "stream_types.PropertyValue": stream_types.PropertyValue,

    "types.UnitDefinition": types.UnitDefinition,
    "stream_types.UnitDefinition": stream_types.UnitDefinition,

    "types.Version": types.Version,
    "stream_types.Version": stream_types.Version,


    "types.LitType": types.LitType,

    "types.Method": types.Method,

    "types.Parameters": types.Parameters,

    "types.Properties": types.Properties,

    "types.UnitType": types.UnitType,

}